name: alistcopy

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      Folder:
        description: '保存目录[没啥用]'
        required: true
        default: 'run'

jobs:
  Onedriver:
    runs-on: ubuntu-latest
    steps:
      - name: 生成Alist的配置文件
        uses: jsdaniell/create-json@v1.2.2
        id: create-json
        with:
          name: "config.json"
          json: ${{ secrets.ALIST_CONFIG }}
      - name: 运行Alist
        run: |
          curl -L -o alist.tar.gz https://github.com/alist-org/alist/releases/download/v3.30.0/alist-linux-amd64.tar.gz
          tar -xzf alist.tar.gz
          mkdir data
          mv config.json data/config.json
          nohup ./alist server > nohupcmd.out 2>&1 &
          ls ${{ github.workspace }}/data
        env:
          ALIST_ADMIN_PASSWORD: admin

      - name: 等Alist运行起来(大概2分钟)
        run: sleep 120s
        shell: bash
      - name: 检查Alist是否成功启动
        run: |
          response_code=$(curl -sL -w "%{http_code}" -u admin:admin http://localhost:5244/ -o /dev/null)
          if [[ $response_code -eq 200 ]]; then
            echo "Alist服务器已成功启动"
          else
            echo "Alist服务器启动失败，状态码：$response_code"
            exit 1
          fi
        shell: bash
        timeout-minutes: 2
