name: alistcopy

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      Folder:
        description: '保存目录[没啥用]'
        required: true
        default: 'run'

jobs:
  Onedriver:
    runs-on: ubuntu-latest
    steps:
      - name: 生成Alist的配置文件
        uses: jsdaniell/create-json@v1.2.2
        id: create-json
        with:
          name: "config.json"
          json: ${{ secrets.ALIST_CONFIG }}
      - name: 运行Alist
        run: |
          curl -L -o alist.tar.gz https://github.com/alist-org/alist/releases/download/v3.30.0/alist-linux-amd64.tar.gz
          tar -xzf alist.tar.gz
          mkdir data
          mv config.json data/config.json
          nohup ./alist server > nohupcmd.out 2>&1 &
          ls ${{ github.workspace }}/data
        env:
          ALIST_ADMIN_PASSWORD: admin
      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl
          
      - name: 检查Alist是否成功启动
        run: |
          while true; do 
              response=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Content-Type: application/json" -H "Authorization: E8OqP8HnB3xx5OtT" -d '{"path": "","page": 1,"per_page": 0,"refresh": false}' http://localhost:5244/api/fs/list); 
              if [ "$response" -eq 200 ]; then
                  break
              else
                  echo "Error: HTTP response code is not 200. Retrying in 5 seconds..."
                  sleep 5
              fi
          done
