name: alistcopy
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      Folder:
        description: '保存目录[没啥用]'
        required: true
        default: 'run'

jobs:
  Onedriver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 增加可用空间 (删除dotnet, android、haskell、CodeQL)
        shell: bash
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
      - name: 生成Alist的配置文件
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "config.json"
          json: ${{ secrets.ALIST_CONFIG }}
      - name: 运行Alist
        run: |
          curl -L -o alist.tar.gz https://github.com/alist-org/alist/releases/download/v3.30.0/alist-linux-amd64.tar.gz
          tar -xzf alist.tar.gz
          mkdir data
          mv config.json data/config.json
          nohup ./alist server > nohupcmd.out 2>&1 &
          ls ${{github.workspace}}/data

      - name: 等Alist运行起来(大概2分钟)
        run: sleep 60s
        shell: bash
        
      - name: rclone
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{secrets.RCLONE_CONF}}
        with:
          args: copy alist:0/ alist:1/
          
   