name: alistcopy
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      Folder:
        description: '保存目录[没啥用]'
        required: true
        default: 'run'

jobs:
  run:
    name: "sync-actions"
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      alist:
        image: xhofe/alist
        env:
          ALIST_ADMIN_PASSWORD: 'admin'
        ports:
        - 5244:5244
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python v4
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: rclone
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: copy a:/ crypt:/
          
   