name: Continuous Curl
on:
  workflow_dispatch:
jobs:
  continuous-curl:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
    - name: install prerequisites
      run: |
        python -m pip install --upgrade pip wheel
        pip install install requests
    - name: Looping Curl
      run: |
        python tools.py
      
