name: Continuous Curl
on:
  workflow_dispatch:
jobs:
  continuous-curl:
    runs-on: ubuntu-latest
    steps:
    - name: Looping Curl
      run: |
        count=0
        while [ $count -lt 10 ]; do
          response_code=$(curl -s -o /dev/null -w "%{http_code}" www.google.com)
           if [ $response_code -eq 200 ]; then
                echo "HTTP 200 OK received. Exiting loop."
                break
            else
                echo "Error: HTTP response code is not 200. Retrying in 5 seconds..."
                sleep 5
            fi
          count=$((count+1))
        done
