name: Continuous Curl
on:
  workflow_dispatch:    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Python script
        run: python tools.py status      
