name: Continuous Curl
on:
  workflow_dispatch:
jobs:
  continuous-curl:
    runs-on: ubuntu-latest
    steps:
    - name: 安装Python3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: 安装所需要的Python信赖
      run: |
        python -m pip install --upgrade pip wheel
        pip install install requests
    - name:  Curl
      run: |
        ls
        cd ..
        ls
        cd ..
        ls
        cd ..
        ls
        cd ..
        ls
        cd ..
        ls
        cd ..
        ls
      
