name: Continuous Curl
on:
  workflow_dispatch:
jobs:
  continuous-curl:
    runs-on: ubuntu-latest
    steps:
    - name: Looping Curl
      run: |
        count=0
        while [ $count -lt 10 ]; do
          curl https://google.com
          count=$((count+1))
          sleep 5  # 在每次循环之间添加延迟，以避免对目标服务器造成过大负载
        done
